### ISSUE TITLE
Uncaught ReferenceError: Dumbass is not defined

### ISSUE THREAD

**Issue by Iserila** [Leclu/Leclu#1]
Dit is geen serieuze issue, mag je gewoon sluiten. Gegroet :)

**Comment by SleepyLeclu** [comment]
how 2 fix?

**Comment by Iserila** [comment]
Ik wou dat ik het wist xD

(Of weet je echt niet hoe dat moet? :o )

**Comment by SleepyLeclu** [comment]
Nee, haha. Ik ben echt NET begonnen met leren xD

**Comment by Iserila** [comment]
Ahhh xD

Waar je je comment kan typen, daaronder heb je 2 knoppen. Een groene "comment" en een grijze close. 

Als je iets in het vak geschreven hebt kun je "Close with comment" kiezen, anders staat er "Close issue" :D
